### PR TITLE
PostgreSQL >= 9.0 gives an error when droping a table with auto-increment

### PR DESCRIPTION
**Pull request by ralfbecker**
Sequences are not detected as dependent on the table and therefore give an error when trying to drop them, after table was dropped.
They are reported as deptype "a"=automatic and "n"=normal, but sequence is droped automatic as for "i"=internal.
Fortunate 9.0+ supports DROP SEQUENCE IF EXITS, so we can use that to not get an error in that case.

### CODE REVIEW

**Comment by ralfbecker** [comment]
Don't pull that right now, there is an other problem in that area, which I want to fix first.

ADOdb code to find the index is a bit simplistic, it assumes index name contain table name, but does not check index is from the concerned table. I have eg. two tables "prefix_name" and "prefix_name_extra", current code will try to drop an index of "prefix_name_extra" when asked to drop it from "prefix_name".

That's easy to fix by checking the table the index is from.

**Comment by dregad** [comment]
OK.

**Comment by dregad** [comment]
@ralfbecker any update on this ? Are you still planning to provide a fix ?

**Comment by dregad** [comment]
@ralfbecker ping

**Comment by mnewnham** [comment]
@ralfbecker , if you have abandoned this, I will close it. You can reopen it if you would like to re-start work on it

**Comment by mnewnham** [comment]
As there has been no response on this, I am closing off the request. Feel free to re-activate

**Pull request closed without merging**
