### PR TITLE
MSSQL driver: support alternative port in connect

### PR DESCRIPTION
**Pull request by merijnvdk**
Fix actually using the alternative port if it was specified. The base
driver class will strip the port from hostname and put it in port
property. So now add it again if it was set.

### CODE REVIEW

**Comment by merijnvdk** [comment]
As this is a pretty straightforward and small fix, is there a reason it has not been looked at? Something more I need to do maybe?

**Comment by dregad** [comment]
> is there a reason it has not been looked at? 

Sorry for the delay, but please keep in mind that we maintain ADOdb in our spare time, and we all have busy lives...

With regards to the PR, I noticed you just pushed a bunch of commits unrelated to the original change, maybe you merged the master branch or something like that... this makes it inconvenient for us to review and merge the changes, so could you please reset your feature branch by rebasing it on top of master and force-push it to github ?

**Comment by atrol** [comment]
@dregad you added a wrong label to it, should certainly be mssql.

**Comment by merijnvdk** [comment]
Hi yes, just wanted to know if there was nothing wrong. As you just noticed I am not that experienced with git yet ;) Bad luck you just happend to look when I messed the feature branch. Should be okay now.

**Pull request merged**
