### PR TITLE
oci8: implement session_mode parameter

### LINKED ISSUE #801: [oci8] Oracle driver should support the session mode argument
Hello,
I need it to support external authentication OCI_CRED_EXT

### PR DESCRIPTION
**Pull request by dregad**
Fixes #801

### CODE REVIEW

**Comment by dregad** [comment]
Please note that the code is untested, as I do not have an Oracle setup available at the moment.

**Comment by dregad** [comment]
@eminemma your feedback on this would be appreciated. Did you get a chance to test the feature, is everything working as expected ? Thanks in advance.

**Comment by eminemma** [comment]
I tried it but it didn't work as expected
I change the line 659 from adodb.inc.php
Actual
$this->connectionParameters[] = array($parameter=>$value);
Fix
$this->connectionParameters[$parameter] = $value;

**Comment by dregad** [comment]
Thanks for testing @eminemma 

You're right, it does not work but your proposed fix is not correct as it would break other drivers relying on _connectionParameters_ property to be a set of parameter/value pairs.

I'll push a fix shortly.

**Comment by eminemma** [comment]
I tried it with the fix and it works correctly, sorry for my English I don't speak that much and it's hard for me to interpret, I use a lot of google to understand

**Comment by dregad** [comment]
Thanks for the feedback. Don't worry about your English, so far it's been (mostly) good enough to understand. What's your native language ?

**Comment by eminemma** [comment]
my native language is spanish, i'm from Latin America

**Comment by dregad** [comment]
Ah in that case I can't help much, my Spanish is just about good enough to order a :beer:

**Pull request merged**
