### PR TITLE
Optimize FieldTypesArray with static variable

### PR DESCRIPTION
**Pull request by joebordes**
I was profiling my application which uses ADOdb and this optimization dropped my timing significantly, but I would like to ask if this change is valid.
The tests I made seemed to be working correctly.

### CODE REVIEW

**Comment by dregad** [comment]
Looks OK to me but if since this is about performance then you should probably use `empty($arr)` instead of `count($arr) > 0`.

@mnewnham thoughts ?

**Comment by joebordes** [comment]
Sounds correct to me. Have a look and let me know if you want me to change anything else.

Thanks!!

**Comment by mnewnham** [comment]
Why not

````php
static $arr = false;
if ($arr) 
    return $arr;

$arr = array();

blah blah blah....
````

**Comment by Mike-Benoit** [comment]
Would be nice to get at least some idea of the actual performance improvement too. Is this a 1% improvement with a certain use case or 50%?

**Comment by Mike-Benoit** [comment]
I think this just introduced another problem along the same lines of: #381.

Anytime data is cached, even in memory, there needs to be a way to clear it when schema changes and static variables make that job much more difficult.

**Comment by dregad** [comment]
Revert?

**Comment by Mike-Benoit** [comment]
I would leave it in place for now, but I think we should figure out a better caching solution as part of #381.

**Comment by dregad** [comment]
OK.

**Comment by dregad** [comment]
> I think this just introduced another problem along the same lines of: #381.
> 
> Anytime data is cached, even in memory, there needs to be a way to clear it when schema changes and static variables make that job much more difficult.

@Mike-Benoit it turns out I've just been hit by this... See #687

**Comment by peterdd** [comment]
@dregad If you revert this you can move out

`$max=$this->_numOfFields;`

out of the loop I think. But probably just a micro optimazation..

**Comment by dregad** [comment]
> If you revert this you can move out
> 
> `$max=$this->_numOfFields;`
> 
> out of the loop I think. But probably just a micro optimization..

OK

Not yet sure if I'll revert or maybe try to find an alternative to using a static variable.

**Pull request merged**
