### PR TITLE
Remove duplicated code from method qstr

### PR DESCRIPTION
**Pull request by stodorovic**
Methods addq and qstr use same code. Call addq from qstr.

### CODE REVIEW

**Comment by mnewnham** [comment]
From [the documentation](https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:addq)

**The function addQ() takes an input string, and applies database specific string quoting. Unlike the method qStr, no pre or post quoting is applied.**

e.g
````php
$string = "Seamus O'Reilly";

print $db->addQ($string);

Seamus O\'Reilly

print $db->qStr($string);

'Seamus O\'Reilly'

````

So if they are in fact the same, that is incorrect. The 2 functions should return different values as shown above.

**Comment by stodorovic** [comment]
They are different functions, but there is "same code" in both methods. It's following code:

https://github.com/ADOdb/ADOdb/blob/97066862ee9d7ae4ada1a0a530330f88cff26e8c/adodb.inc.php#L2943-L2967

Only differences are:

`return  "'".str_replace("'",$this->replaceQuote,$s)."'";`
vs
`return  str_replace("'",$this->replaceQuote,$s);`

`return "'$s'";`
vs
`return $s; `

`return "'".str_replace("\\'",$this->replaceQuote,$s)."'";`
vs
`return str_replace("\\'",$this->replaceQuote,$s); `

So, _qstr_ returns:
`return "'".$this->addq($s,$magic_quotes)."'";`

This PR simplifies current code in function qstr.

**Comment by mnewnham** [comment]
Ok, I see what you are doing there. This may be problematical as you are removing the core system code and replacing it with a call to a driver specific method. So while what you have done may be correct for the mssql driver, we don't know that this is true for every other one. Can I suggest a safer approach would be to extend the qstr method into the driver and place your changes there.

**Comment by dregad** [comment]
@stodorovic are you planning to address the review comments ?

**Comment by dregad** [comment]
@stodorovic as you have not provided any feedback or updated the PR, I suppose you are not interested in pursuing this. I am therefore closing this pull request for now, feel free to reopen it if you intend to follow Mark's suggestion.

**Pull request closed without merging**
