### PR TITLE
Replace deprecated MySQL BINARY operator

### LINKED ISSUE #942: Replace deprecated MySQL `BINARY` operator
The BINARY operator has been deprecated in MySQL 8.0.27 [[1](https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#operator_binary)].

This is used in Sessions management to force a case-sensitive comparison on the Session key.

I noticed this while analyzing #941 (see https://github.com/ADOdb/ADOdb/issues/941#issuecomment-1481638054).

### PR DESCRIPTION
**Pull request by dregad**
This should fix #942.

As I do not actually use ADOdb Sessions in production myself, I would appreciate if someone who does could test this code and confirm it does not introduce any regressions (@mariobernheim maybe ?).

Thanks in advance, looking forward to receiving your feedback.

### CODE REVIEW

**Comment by mariobernheim** [comment]
> This should fix #942.
> 
> As I do not actually use ADOdb Sessions in production myself, I would appreciate if someone who does could test this code and confirm it does not introduce any regressions (@mariobernheim maybe ?).
> 
> Thanks in advance, looking forward to receiving your feedback.

We've switched this to production now and will post back with findings :)

**Comment by dregad** [comment]
Thanks @mariobernheim, your help is appreciated !

**Comment by dregad** [comment]
@mariobernheim You have not posted back, should I assume that everything is working fine ?

**Comment by mariobernheim** [comment]
@dregad we wanted to give it a full week in production to capture any issues, so far, no issues have been reported!

**Comment by dregad** [comment]
Awesome, thanks for the feedback. I'll merge this PR later this week then.

**Pull request merged**
