### PR TITLE
Fix queries returning no data in ASSOC fetch mode

### LINKED ISSUE #20: Possibly broken modification to Class ADORecordSet function GetAssocKeys V5.19  23-Apr-2014
Hi,

Many thanks to everybody who has made this such a brilliant piece of kit which I have used in numerous projects :-)

Please excuse me if this is a duplicate or if I have overlooked something.

A problem appears to have been introduced into adodb.inc.php V5.19  23-Apr-2014 

Class ADORecordSet function GetAssocKeys 

I've had to change line 3505 in my production system

/*Change by Chris Barnes 2014-05-07 after problems with GetRowAssoc and function _fetch() in adodb-ibase.inc.php
*Previously: $this->bind[$key] = $val;
*Now: $this->bind[$val] = $i;
* This reflects the functionality of earlier versions of this function
* Take special note of the comment: "# This should not happen... trigger error ?" in GetRowAssoc
*/

Many thanks

Chris

### PR DESCRIPTION
**Pull request by dregad**
@clarumedia 
@Illydth 
@jpSimkins

This should (hopefully) fix #20 and #93. Your testing and feedback would be appreciated.

### CODE REVIEW

**Comment by clarumedia** [comment]
Please excuse my ignorance of Github:  How do I get your new dev version of the whole ADODBPHP library so I can test ?

**Comment by dregad** [comment]
@clarumedia you can download a zip from https://github.com/dregad/ADOdb/archive/fetch-mode-assoc-case.zip, or if you're using git, you can clone the feature branch from my fork of the repo e.g. 
`git clone -b fetch-mode-assoc-case https://github.com/dregad/ADOdb.git`

**Comment by clarumedia** [comment]
Thank you for the ZIP file.
I've run the same test as before:

-- code --
require_once("ADOdb-fetch-mode-assoc-case/adodb.inc.php");

$ADODB_FETCH_MODE=ADODB_FETCH_ASSOC;

$objInterbaseDB = &ADONewConnection('ibase');

$arrInterbaseConnectInfo=array();
$arrInterbaseConnectInfo["db_file"]="DBFILENAME";
$arrInterbaseConnectInfo["db_username"]="SOMEUSER";
$arrInterbaseConnectInfo["db_password"]="SOMEPASSWORD";

$objInterbaseDB->PConnect($arrInterbaseConnectInfo["db_file"],$arrInterbaseConnectInfo["db_username"],$arrInterbaseConnectInfo["db_password"]);

$sql="SELECT * FROM UNITS WHERE UNIT_NAME='Shots'";

$rs=$objInterbaseDB->execute($sql);
print_r($rs->GetRowAssoc(0)); print_r($rs->bind); print_r($rs->fields);
print_r($rs->GetRowAssoc(1)); print_r($rs->bind); print_r($rs->fields);
echo "ADODB_ASSOC_CASE=".ADODB_ASSOC_CASE."\n";

Result:

Array
(
    [unit_id] => 
    [unit_name] => 
    [ratio] => 
    [unit_type] => 
)
Array
(
    [unit_id] => 0
    [unit_name] => 1
    [ratio] => 2
    [unit_type] => 3
)
Array
(
    [UNIT_ID] => 5
    [UNIT_NAME] => Shots
    [RATIO] => 0.00061613001162186
    [UNIT_TYPE] => 1
)
Array
(
    [unit_id] => 
    [unit_name] => 
    [ratio] => 
    [unit_type] => 
)
Array
(
    [unit_id] => 0
    [unit_name] => 1
    [ratio] => 2
    [unit_type] => 3
)
Array
(
    [UNIT_ID] => 5
    [UNIT_NAME] => Shots
    [RATIO] => 0.00061613001162186
    [UNIT_TYPE] => 1
)
ADODB_ASSOC_CASE=2

**Comment by dregad** [comment]
Does that mean it works ?

**Comment by clarumedia** [comment]
Hi Damien,

I'm not entirely sure !!
The output from my hacked version is:

Array
(
    [UNIT_ID] => 5
    [UNIT_NAME] => Shots
    [RATIO] => 0.00061613001162186
    [UNIT_TYPE] => 1
)
Array
(
    [UNIT_ID] => 0
    [UNIT_NAME] => 1
    [RATIO] => 2
    [UNIT_TYPE] => 3
)
Array
(
    [UNIT_ID] => 5
    [UNIT_NAME] => Shots
    [RATIO] => 0.00061613001162186
    [UNIT_TYPE] => 1
)
Array
(
    [UNIT_ID] => 5
    [UNIT_NAME] => Shots
    [RATIO] => 0.00061613001162186
    [UNIT_TYPE] => 1
)
Array
(
    [UNIT_ID] => 0
    [UNIT_NAME] => 1
    [RATIO] => 2
    [UNIT_TYPE] => 3
)
Array
(
    [UNIT_ID] => 5
    [UNIT_NAME] => Shots
    [RATIO] => 0.00061613001162186
    [UNIT_TYPE] => 1
)
ADODB_ASSOC_CASE=2



On 24 April 2015 at 14:55, Damien Regad <notifications@github.com> wrote:

> Does that mean it works ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ADOdb/ADOdb/pull/95#issuecomment-95940811>.
>



-- 
------------------------------

Chris Barnes
m: 07881 540 974
e: chris@barnesconsultants.com
w: www.barnesconsultants.com

**Comment by dregad** [comment]
Chris,

I guess the *real* test would be to use your own application... 

The code I gave you was just for me to understand what was going on, it is by no means a test case (the parameter given to GetRowAssoc forces the case conversion to lowercase, which is most likely not something that would happen in a real-life situation).

**Comment by clarumedia** [comment]
Hey Damien,

I've swapped out the adodb library in my dev environment (which also makes heavy use of MySQL) and run the offending scripts.
It's all looking good to me so far.
It will get pushed into my production system on the next release which will be within a couple of days.

If you'd like to write some tests, I'd be happy to run them for you.

Many thanks

Chris

**Comment by dregad** [comment]
I'm actually planning to release ADOdb 5.20 very soon (in fact, the version you downloaded includes most if not all of what will actually go in), in case you want to wait to have an "official" release in your production system.

**Comment by clarumedia** [comment]
I will hang on for 5.20.
Nice work !
Many thanks.
Chris

On 24 April 2015 at 15:51, Damien Regad <notifications@github.com> wrote:

> I'm actually planning to release ADOdb 5.20 very soon (in fact, the
> version you downloaded includes most if not all of what will actually go
> in), in case you want to wait to have an "official" release in your
> production system.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ADOdb/ADOdb/pull/95#issuecomment-95953359>.
>



-- 
------------------------------

Chris Barnes
m: 07881 540 974
e: chris@barnesconsultants.com
w: www.barnesconsultants.com

**Comment by clarumedia** [comment]
Hi Damien, 

On reflection, even if my application appears to work OK, It does worry me that the results of your original test are different to my earlier / hacked version. 

Many thanks. 

Chris

**Comment by dregad** [comment]
Hi Chris

Following up on your note:

> On reflection, even if my application appears to work OK, It does worry me that the results of your original test are different to my earlier / hacked version.

I compared the output of the test script (which, again, is not really a proper test case, but it nevertheless demonstrates my point), between the 3 versions of ADOdb involved:

- 5.18, working as per your initial bug report, 
- 5.19, the version which introduced the bug, and 
- 5.20 fix (i.e. the code in this pull request).

Please consider the results in the table below (*Case* column = value of *ADODB_ASSOC_CASE* constant). Note that I also removed the 2nd print_r statement (`$rs->GetRowAssoc(1)`) as it always returns the same results as the first one. 

Case | V5.18 | V5.19 | V5.20 fix
---- | ---- | ---- | ----
0 | first_name => Robert | first_name =>  | first_name => Robert
0 | first_name => 0 | first_name =>  | first_name => 0
0 | first_name => Robert | first_name => FIRST_NAME | first_name => Robert
1 | first_name =>  | first_name =>  | first_name => 
1 | first_name => 0 | first_name => first_name | first_name => 0
1 | FIRST_NAME => Robert | FIRST_NAME =>  | FIRST_NAME => Robert
2 | first_name =>  | first_name =>  | first_name => 
2 | first_name => 0 | first_name =>  | first_name => 0
2 | FIRST_NAME => Robert | FIRST_NAME =>  | FIRST_NAME => Robert

As you can see, my fix effectively reverts the code's behavior to how it was in 5.18, which IMO makes it correct, regardless of what your "hacked" version does.

Now we could probably argue whether it's correct for the function not to return a binding when ADODB_ASSOC_CASE is set to *ADODB_ASSOC_CASE_UPPER* or *ADODB_ASSOC_CASE_NATIVE*, but even if it is not, it should in any case be tracked as a different bug which I invite you to open if you feel this needs fixing.

Let me know your thoughts.

**Comment by clarumedia** [comment]
Hi Damien,

Many thanks for your reply and for the work you have been doing on this
project.

I think you have done the right thing in ensuring the functionality of
V5.20 replicates the functionality of V5.18 and I appreciate the clarity of
your test results.

I take it that the test results for Oracle and MySQL are also the same
between V5.18 and V5.20 ?

I agree that the issue of ADODB_ASSOC_CASE / ADODB_ASSOC_CASE_UPPER /
ADODB_ASSOC_CASE_NATIVE is a separate issue.

Thank you again !!

Chris





On 11 May 2015 at 22:57, Damien Regad <notifications@github.com> wrote:

> Hi Chris
>
> Following up on your note:
>
> On reflection, even if my application appears to work OK, It does worry me
> that the results of your original test are different to my earlier / hacked
> version.
>
> I compared the output of the test script (which, again, is not really a
> proper test case, but it nevertheless demonstrates my point), between the 3
> versions of ADOdb involved:
>
>    - 5.18, working as per your initial bug report,
>    - 5.19, the version which introduced the bug, and
>    - 5.20 fix (i.e. the code in this pull request).
>
> Please consider the results in the table below (*Case* column = value of
> *ADODB_ASSOC_CASE* constant). Note that I also removed the 2nd print_r
> statement ($rs->GetRowAssoc(1)) as it always returns the same results as
> the first one.
>   Case V5.18 V5.19 V5.20 fix   0 first_name => Robert first_name => first_name
> => Robert  0 first_name => 0 first_name => first_name => 0  0 first_name
> => Robert first_name => FIRST_NAME first_name => Robert  1 first_name => first_name
> => first_name =>  1 first_name => 0 first_name => first_name first_name
> => 0  1 FIRST_NAME => Robert FIRST_NAME => FIRST_NAME => Robert  2 first_name
> => first_name => first_name =>  2 first_name => 0 first_name => first_name
> => 0  2 FIRST_NAME => Robert FIRST_NAME => FIRST_NAME => Robert
>
> As you can see, my fix effectively reverts the code's behavior to how it
> was in 5.18, which IMO makes it correct, regardless of what your "hacked"
> version does.
>
> Now we could probably argue whether it's correct for the function not to
> return a binding when ADODB_ASSOC_CASE is set to *ADODB_ASSOC_CASE_UPPER*
> or *ADODB_ASSOC_CASE_NATIVE*, but even if it is not, it should in any
> case be tracked as a different bug which I invite you to open if you feel
> this needs fixing.
>
> Let me know your thoughts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ADOdb/ADOdb/pull/95#issuecomment-101060396>.
>



-- 
------------------------------

Chris Barnes
m: 07881 540 974
e: chris@barnesconsultants.com
w: www.barnesconsultants.com

**Comment by Illydth** [comment]
@dregad Apologies for the miss on this, I haven't checked in with Github's notifications in a LONG time.

Sometime in the next couple weeks I should be back on to the project that's using this, and at that point I'll give 5.20 a try and see what happens, however based upon your test cases above I've got every confidence it's what I need.

Thanks VERY much for the work you've done on this, it's a GREAT library.

**Comment by dregad** [comment]
@Illydth thanks for your feedback, it's much appreciated. If you do find a bug with 5.20 when you get around to testing it, do not hesistate to open an issue and we'll do our best to fix it.

**Pull request closed without merging**
