### PR TITLE
Fix issue #970

### PR DESCRIPTION
**Pull request by joebordes**

### CODE REVIEW

**Review by dregad — CHANGES_REQUESTED** [review]
I'd rather not have a test SQLite database stored in the repository.

If the DB cannot be created programmatically by the test script, then provide the necessary instructions for the developer to do it manually in a comment.

Otherwise, everything looks good to me.

**Comment by joebordes** [comment]
deleted the database and added code to create it programmatically

**Comment by dregad** [comment]
Many thanks for your contribution !

**Comment by dregad** [comment]
@joebordes Apologies for resurrecting this after nearly 2 years, but I just realized that the switch from _adodb_date()_ to sqlite3 internal _strftime()_ function introduced by this PR is not correct and causes a regression, because it alters the behavior of the [SQLDate() method](https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:sqldate) which expects PHP-style date formats, while the code introduced by this PR switches to strftime format (e.g. `Ymd` => `%Y%m%d`).

I'll open a new PR to fix this regression.

**Comment by joebordes** [comment]
No problem at all. I'm not sure I can help, but reach out as needed. I will try

**Pull request merged**
