### PR TITLE
Mysqli notice and two PHP7 fixes

### PR DESCRIPTION
**Pull request by marinaglancy**
Reported also in https://github.com/ADOdb/ADOdb/issues/168

### CODE REVIEW

**Comment by dregad** [comment]
*Note to self: next time, comment on the* files changed *tab and not directly in the commits...*

**Comment by marinaglancy** [comment]
apologies for putting separate changes in the same commit. I absolutely do not mind you replacing my commit(s) with another solution and rejecting this pull request. We can also pull your changes into moodle instead of my fix, we are only testing now and will not release until the end of this week.

I added a unittest for the _colonscope function in moodle (because there is pretty much no other way we can test it), I have just run it with $m[1] and it works the same: https://github.com/marinaglancy/moodle/commit/cc3048eb410396c3230c8a76824c859b5f597c3e
Also the use of "create_function()" is inline with moodle coding style, I know that most of other projects prefer anonymous functions.

As for the constructor, I thought that you may prefer to remove it completely because it repeats the parent one.

**Comment by marinaglancy** [comment]
Also no preferences on @ operator. The bigger question is if this is actually the correct place to put the fix for the error we are experiencing. We were trying to figure out why it is happening at all.

This is the error we were having: https://tracker.moodle.org/browse/MDL-52286?focusedCommentId=385668&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-385668
My first intention was to remove destructor but then I started looking why other db, such as postgres, pass our unittests and noticed the @ in the _close() method.

**Comment by marinaglancy** [comment]
update from our integration team - we just hit the same on mssql (php5): https://tracker.moodle.org/browse/MDL-52512
http://pastebin.com/UaLnGV2c
I'll create a separate request, I promise :)

**Comment by marinaglancy** [comment]
I created #170 for the destructor-related failures

**Comment by dregad** [comment]
> the use of "create_function()" is inline with moodle coding style, I know that most of other projects prefer anonymous functions

My point was not against use of `create_function()` vs a closure, but rather to call `_colontrack()` directly as explained in https://github.com/marinaglancy/ADOdb/commit/dff32013c1f2f1e51ea8be59d447280d60362e33#commitcomment-14962888

> As for the constructor, I thought that you may prefer to remove it completely because it repeats the parent one.

You're right.

> Also no preferences on @ operator. The bigger question is if this is actually the correct place to put the fix for the error we are experiencing. 

There is way too much use of @ operator for my taste in this library ;-)

**Comment by dregad** [comment]
preg_replace issue (#168) has been fixed in bdeb28f214c29a54a88cef995e251702f7181ab7 and follow-up commit c32f1525136ff3afcf1e3ed30a17818b1bcd1731.

Destructor issue (#170) is fixed in 59e93d9b2ed7e8fc040f35a1eb228ae222116112, dcbe478834b607f0f572b934fbc1b4e137688a7f and 745a02a7533b744c1a14a8bb0b41fea96c41ac14

**Pull request closed without merging**
