### PR TITLE
Doc comment updates

### PR DESCRIPTION
**Pull request by jasonmm**
Currently I have only modified the `adodb.inc.php` file (along with two other small changes).  If this pull request is accepted then I will continue with other files.

### CODE REVIEW

**Comment by mnewnham** [comment]
Jason, This looks good. @dregad and I are currently trying to put together an initial coding standards set for the project, so could we keep this on hold for a few days. The standard is more than likely going to be based on PEAR standards using PHP_codesniffer, so if you could check the code against that, it would be even more helpful. 

Thanks

Mark

**Comment by jasonmm** [comment]
Running `phpcs` outputs `FOUND 6654 ERRORS AND 146 WARNINGS AFFECTING 3285 LINES`. Are these items that you would like to be fixed before accepting this pull request?

I have never used PHP_CodeSniffer before, but the output also mentions `PHPCBF CAN FIX THE 5997 MARKED SNIFF VIOLATIONS AUTOMATICALLY`.  Which makes much of the work sound pretty easy.  Would it be helpful for me to run `phpcbf` on the file?

**Comment by mnewnham** [comment]
Absolutely. This should be able to fix about 90% of the issues

**Comment by dregad** [comment]
Hello Jason. May I also kindly ask you, in the interest of keeping our git history as linear as possible, to rebase your branch on top of latest master instead of merging ? Thanks in advance.

**Comment by jasonmm** [comment]
I understand. Thank you to both of you. There are many small items in the Code Sniffer output.  It may take me a while to get through the ones that I can fix.

**Comment by dregad** [comment]
Hi Jason,

Don't worry about it and take your time, there is no rush. Your contribution is greatly appreciated, and do let us know if you need help.

**Comment by jasonmm** [comment]
I have rebased my branch onto master.  I also fixed many of the PHPCS items.

Turns out there are a number of the PHPCS items that are for actual code.  I didn't want to change actual code for fear of breaking things.  I also tried not to change existing comments or add tags like `@link`, `@package`, etc...

Is there anything further that should be done?

**Comment by laurent-n** [comment]
Hello Jason,
Thanks for this patch, I use PHPStorm which is doing type check based on phpdoc type, so I've done a quick review on my most used function, and I suggest theses changes : 
getall inputarr is bool|array , return boll|array
getrow inputarr is bool|array , return bool|array
GetOne & GetCol, execute,getassoc  inputarr is bool|array  

I hope this patch will be integrated in the next release.

Thanks again for your contribution.

**Comment by jasonmm** [comment]
@laurent-n, thank you.  With issues #192 and #193 I think this pull request may be outdated now.  The work done on those issues will naturally take care of the items included in this pull request.

**Comment by laurent-n** [comment]
I've pushed a commit on a pull request with few documentation changes on some of the most used method applied on a fresh update.
Hopping it can reduce warnings and errors on static analysis tools.

**Comment by dregad** [comment]
@laurent-n thanks for your message. Considering that this PR is stale, I would suggest - if you don't mind - that you open a new one with your changes, and I'll close this one.

**Comment by jasonmm** [comment]
It has been mentioned a couple of times that this pull request should be closed in favor of more recent work. Finally closing it now. 😄

**Pull request closed without merging**
