### PR TITLE
Fixes issue https://github.com/ADOdb/ADOdb/issues/121

### PR DESCRIPTION
**Pull request by CreatrixTeam**

### CODE REVIEW

**Comment by dregad** [comment]
For future patch submissions, may I kindly ask you to 

1. refrain from opening *both* an issue *and* a pull request like you just did, it's redundant...  
If you have a patch, it is sufficient to put everything in the PR; the only case where we would have both, is if you're submitting a patch for a pre-existing issue
2. make sure each commit message includes a complete description of the issue it addresses. I suggest reading the [Git commit message guidelines](https://www.mantisbt.org/wiki/doku.php/mantisbt:git_commit_messages) I wrote some time ago for MantisBT.

Thanks.

**Comment by CreatrixTeam** [comment]
Thank you.

Regarding 1,  if you would give us permission, we would like to continue doing things the way we are doing them now. We use issue to discuss, track and confirm. A submitted issue does not guarantee an issue exists. An issue exists regardless whether we patch or not. And a patch does not guarantee a request for pull. If you do not give permission, we shall abide by your request. We are waiting for your response.

**Comment by dregad** [comment]
From my perspective, tracking and confirmation can be done just as effectively in a pull request. Opening an issue on top of the PR just creates additional overhead, even more so if the PR is just a series of references without any actual text (like this one). That makes keeping track and reviewing things more difficult for me. If a patch is rejected, or the underlying issue determined not to be valid, the PR will simply be closed without merging.

**Comment by CreatrixTeam** [comment]
Thank you. 

Perhaps we did not explain our selves well. One might think there is an issue, but it would be better to wait for confirmation before starting to program something. In any case, we shall abide by your request, at least in the case where we are sure an issue is indeed an issue like in this case, and we shall do our best to abide in other cases.

**Comment by dregad** [comment]
Clearly in such case where you're not sure about an issue and the patch is not something trivial like this PR, then a 2-step approach is the better approach... thus no objection to have both issue + PR when necessary. Use common sense but please make the PR title more descriptive than a simple link.

**Pull request closed without merging**
