### PR TITLE
Prevent str_replace NULL test error in PHP 8.1 qstr() methods

### PR DESCRIPTION
**Pull request by mnewnham**

### CODE REVIEW

**Review by dregad — APPROVED** [review]
LGTM.

You deserve extra credits for creating the longest branch name I have ever seen 😉

**Comment by dregad** [comment]
That said, you really should avoid using special chars like `$` and `|` in a branch name, as it causes Git to choke when referencing it without quotes

```
~/dev/adodb (master)$ git co 999-adodb-oci8incphp1585-str_replace-passing-null-to-parameter-3-$subject-of-type-array|string-is-deprecated
error: pathspec '999-adodb-oci8incphp1585-str_replace-passing-null-to-parameter-3--of-type-array' did not match any file(s) known to git
string-is-deprecated: command not found
```

**Comment by mnewnham** [comment]
> That said, you really should avoid using special chars like `$` and `|` in a branch name, as it causes Git to choke when referencing it without quotes
> 
> ```
> ~/dev/adodb (master)$ git co 999-adodb-oci8incphp1585-str_replace-passing-null-to-parameter-3-$subject-of-type-array|string-is-deprecated
> error: pathspec '999-adodb-oci8incphp1585-str_replace-passing-null-to-parameter-3--of-type-array' did not match any file(s) known to git
> string-is-deprecated: command not found
> ```

Interestingly, this is the branch name that git generated for me, and I tend to accept them unread. I've seen this issue with special characters in the name before - jira creates even longer names for branches than git.

**Comment by dregad** [comment]
> this is the branch name that git generated for me

Oh well 🤷 

Removed milestone and tags, as I did not realize that this was fixing exising issue #999, which was already properly tagged.

**Pull request merged**
