### PR TITLE
Remove references to ADOdb Extension

### PR DESCRIPTION
**Pull request by dregad**
For review. See #269, #270 .

### CODE REVIEW

**Comment by dregad** [comment]
@mnewnham any comments ?
@peterdd if you have the opportunity to test this with the provider that was causing issues for your Flyspray user, it would be appreciated.

**Comment by peterdd** [comment]
I will try, but prob. no time before october.

**Comment by mnewnham** [comment]
We definitely do need to remove these references, in some sense I think the whole thing was a distraction from the core product. @dregad , I believe your approach to this is fine

**Comment by dregad** [comment]
Thanks for the feedback. I will merge this in as-is, and if @peterdd later realizes this is causing issues, then we can make the necessary adjustments.

**Pull request closed without merging**
