### PR TITLE
Add "Update or Insert" (UPSERT) functionality in AutoExecute

### PR DESCRIPTION
**Pull request by chc88**
Very frequently we see the need to have an Update or Create functionality.
When this is the case you would like to update an existing record if possible, and create it when it is not yet present in the table.

In this pull request the AutoExecute function is extended with this "UPSERT" functionality.

To check if a record already exists the PO_RecordCount function is used.

### CODE REVIEW

**Comment by Mike-Benoit** [comment]
Doesn't this introduce race conditions between the select and insert/update calls?

What if a database supports UPSERT natively? Like recent versions of PostgreSQL and I'm pretty sure Oracle/MS-SQL too? It would be nice if we had an easy way to utilize the native functionality which should avoid the worst part of these race conditions. Of course this would require plumbing into the driver itself to generate the necessary DB specific SQL.

**Comment by chc88** [comment]
Mike, thanks for your feedback. You have a point there.

I could relocate the logic to ADOConnection so it could be overridden in the driver-specific classes (and in AutoExecute it would be the same as for the getUpdateSQL or getInsertSQL).

As for the racing conditions, in my usecases I have not seen it happen (yet). 
The code in AutoExecute could be wrapped with the Transaction-functions when available (how could we check if the current driver accepts transctions?)

Let me know what you think.

**Comment by Mike-Benoit** [comment]
Might want to let @dregad @mnewnham weigh in on the best way to delegate this functionality to the drivers.

As for the race condition issue, the only way I'm aware of fixing that is to start a serializable transaction which can really hurt performance, and should throw an exception if it happens to fail/timeout and offer a way to retry. My guess is that if we tried to implement this that way it would have so many drawbacks to be useless in the real world, at least for anyone that cares about performance and reliability. It also will cause problems for the load balancing class I proposed a few years ago...

Don't get me wrong, supporting upsert would be awesome, but it's not an easy thing to do for databases that don't already support it natively. See the following for a interesting read: https://www.depesz.com/2012/06/10/why-is-upsert-so-complicated/

**Comment by chc88** [comment]
Ok, with the comments of dregad I agree on not taking further actions on this pull-request

**Pull request closed without merging**
