### PR TITLE
Update adodb-pdo_mysql.inc.php

### PR DESCRIPTION
**Pull request by dezertdezine**
Remove extraneous comma in $fmtTimeStamp

### CODE REVIEW

**Comment by dregad** [comment]
@dezertdezine thanks for the PR, I assume this fixes #531 ?

**Comment by dezertdezine** [comment]
@dregad indeed it does, I should have mentioned that.

**Comment by dregad** [comment]
This was fixed in 6898449725f4910524b2afb84bebaf602a784fe2

**Comment by ooglek** [comment]
WHOOHOO! Thank you!

**Pull request closed without merging**
